// flow-typed signature: f413f789f88254bff66aa8d7ef721dea
// flow-typed version: <<STUB>>/chai-as-promised_v6.0.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chai-as-promised'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'chai-as-promised' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chai-as-promised/lib/chai-as-promised' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chai-as-promised/lib/chai-as-promised.js' {
  declare module.exports: $Exports<'chai-as-promised/lib/chai-as-promised'>;
}
