// flow-typed signature: e547d674ea122e4c8961520bedf08879
// flow-typed version: <<STUB>>/eslint-config-mostaza-base_v^1.13.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-mostaza-base'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-mostaza-base' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-mostaza-base/rules' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-mostaza-base/index' {
  declare module.exports: $Exports<'eslint-config-mostaza-base'>;
}
declare module 'eslint-config-mostaza-base/index.js' {
  declare module.exports: $Exports<'eslint-config-mostaza-base'>;
}
declare module 'eslint-config-mostaza-base/rules.js' {
  declare module.exports: $Exports<'eslint-config-mostaza-base/rules'>;
}
