// flow-typed signature: 5faceb3e530afb50ec9c65a59aa50c72
// flow-typed version: <<STUB>>/parse-utils_v^2.0.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'parse-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'parse-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'parse-utils/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'parse-utils/lib/index.js' {
  declare module.exports: $Exports<'parse-utils/lib/index'>;
}
