export default {
  USER_NOT_LOGGED_IN: 'user not logged in',
  ACCOUNT_NOT_FOUND: 'account not found',
  ACCOUNT_ALREADY_ACTIVATED: 'account already activated',
  REQUIRED_FISCAL_CODE: 'fiscalCode is required',
  REQUIRED_FULL_NAME: 'fullName is required',
  REQUIRED_MESSAGE: 'message is required',
  REQUIRED_CATEGORY: 'category is required',
  REQUIRED_LIST_TEXT: 'listText is required',
  REQUIRED_FORM_TEXT: 'formText is required',
  REQUIRED_CSV_IMPORT_ID: 'csvImportId is required',
  REQUIRED_CSV: 'csv is required',
  REQUIRED_TICKET_ID: 'ticketId is required',
  NOT_FOUND_CSV_IMPORT: 'csvImport not found',
  INVALID_EXP_DATE: 'invalid expDate',
  ALREADY_IN_USE_FISCAL_CODE: 'fiscalCode already in use',
  CSV_EMPTY_FULL_NAME: 'Nome completo assente',
  CSV_EMPTY_FISCAL_CODE: 'Codice fiscale assente',
  CSV_DUPLICATE_FISCAL_CODE: 'Codice fiscale duplicato'
}
